name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - numpy>=1.26.0
  - opensimplex>=0.4.5
  - flake8
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pip
  - pip:
      - veilbreakers-mcp @ git+https://github.com/Sharks820/veilbreakers-gamedev-toolkit.git#subdirectory=Tools/mcp-toolkit
