from typing import Any

def subplots(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...
def colorbar(*args: Any, **kwargs: Any) -> Any: ...
def tight_layout(*args: Any, **kwargs: Any) -> None: ...
def savefig(*args: Any, **kwargs: Any) -> None: ...
def close(*args: Any, **kwargs: Any) -> None: ...
