from __future__ import annotations

from typing import Any, Iterable, Iterator, Self


class Vector:
    x: float
    y: float
    z: float
    length: float

    def __init__(self, seq: Iterable[float] = ...) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __add__(self, other: Any) -> Self: ...
    def __sub__(self, other: Any) -> Self: ...
    def __mul__(self, other: Any) -> Self: ...
    def __rmul__(self, other: Any) -> Self: ...
    def __truediv__(self, other: Any) -> Self: ...
    def copy(self) -> Self: ...
    def normalized(self) -> Self: ...
    def normalize(self) -> None: ...
    def dot(self, other: Any) -> float: ...
    def cross(self, other: Any) -> Self: ...
    def lerp(self, other: Any, factor: float) -> Self: ...
    def angle(self, other: Any, fallback: Any = ...) -> float: ...
    def to_track_quat(self, track: str, up: str) -> Quaternion: ...


class Matrix:
    def __init__(self, rows: Iterable[Iterable[float]] = ...) -> None: ...
    def __matmul__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def inverted(self) -> Self: ...
    def transposed(self) -> Self: ...
    def to_euler(self) -> Euler: ...

    @staticmethod
    def Rotation(angle: float, size: int, axis: str | Vector) -> Matrix: ...


class Euler:
    x: float
    y: float
    z: float

    def __init__(self, seq: Iterable[float] = ..., order: str = ...) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def to_matrix(self) -> Matrix: ...


class Quaternion:
    def __init__(self, seq: Iterable[float] = ...) -> None: ...
    def to_euler(self) -> Euler: ...
    def to_matrix(self) -> Matrix: ...


class Color(Vector): ...


noise: Any


def __getattr__(name: str) -> Any: ...
