"""Bundle K — terrain_stochastic_shader.

Implements Heitz & Neyret 2019 "Histogram-Preserving Blending" stochastic
tile-sampling for terrain PBR layers.  Full implementation:

1. ``build_stochastic_sampling_mask`` — per-tile hash offsets (UV translation
   + per-tile rotation angle) using the Heitz 2019 triangular-basis approach.
   Histogram-preserving blending via rank-based equalisation keeps the output
   offset distribution uniform so tiled PBR textures show no brightness drift.

2. ``StochasticShaderTemplate`` — full shader parameter dataclass including
   histogram-preserving blend fields, contrast correction, and UV rotation
   range, consumed by the Unity HLSL template importer.

3. ``export_unity_shader_template`` — emits a valid Unity shader asset: a
   ``.shader`` file containing a complete HLSL stochastic sampling
   implementation (Heitz 2019 triangular-basis) alongside a JSON manifest.

4. ``pass_stochastic_shader`` — wires template + mask into stack channels.

Pure numpy, no bpy.
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

logger = logging.getLogger(__name__)

from .terrain_semantics import (
    BBox,
    PassDefinition,
    PassResult,
    TerrainMaskStack,
    TerrainPipelineState,
)

# ---------------------------------------------------------------------------
# HLSL stochastic sampling template (Heitz 2019 triangular-basis)
# ---------------------------------------------------------------------------

# Full HLSL implementation of histogram-preserving stochastic tiling.
# This is the shader code exported to Unity as a .shader asset.
_HLSL_STOCHASTIC_SHADER = r"""// VeilBreakers Terrain — Stochastic Tiling Shader
// Based on: Heitz & Neyret 2019 "Histogram-Preserving Blending Operator"
// Auto-generated by terrain_stochastic_shader.py — do not edit manually.

Shader "VeilBreakers/TerrainLit_Stochastic_{TEMPLATE_ID}"
{{
    Properties
    {{
        _BaseMap           ("Albedo",            2D)    = "white" {{}}
        _BumpMap           ("Normal Map",        2D)    = "bump"  {{}}
        _MetallicGlossMap  ("Metallic/Smoothness",2D)   = "white" {{}}
        _OcclusionMap      ("Occlusion",         2D)    = "white" {{}}
        _StochasticSeed    ("Stochastic Seed",   Float) = {STOCHASTIC_SEED}
        _BlendSharpness    ("Blend Sharpness",   Float) = {BLEND_SHARPNESS}
        _RandomnessStrength("Randomness Strength",Float)= {RANDOMNESS_STRENGTH}
        _TileSize          ("Tile Size (m)",     Float) = {TILE_SIZE}
        _ContrastCorrection("Contrast Correction",Float)= {CONTRAST_CORRECTION}
        _UVRotationRange   ("UV Rotation Range", Float) = {UV_ROTATION_RANGE}
    }}

    SubShader
    {{
        Tags {{ "RenderType"="Opaque" "RenderPipeline"="UniversalRenderPipeline" }}
        LOD 300

        Pass
        {{
            Name "ForwardLit"
            Tags {{ "LightMode"="UniversalForward" }}

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_fog
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            TEXTURE2D(_BaseMap);          SAMPLER(sampler_BaseMap);
            TEXTURE2D(_BumpMap);          SAMPLER(sampler_BumpMap);
            TEXTURE2D(_MetallicGlossMap); SAMPLER(sampler_MetallicGlossMap);
            TEXTURE2D(_OcclusionMap);     SAMPLER(sampler_OcclusionMap);

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseMap_ST;
                float  _StochasticSeed;
                float  _BlendSharpness;
                float  _RandomnessStrength;
                float  _TileSize;
                float  _ContrastCorrection;
                float  _UVRotationRange;
            CBUFFER_END

            struct Attributes {{ float4 positionOS : POSITION; float2 uv : TEXCOORD0; float3 normalOS : NORMAL; }};
            struct Varyings   {{ float4 positionHCS : SV_POSITION; float2 uv : TEXCOORD0; float3 normalWS : TEXCOORD1; UNITY_FOG_COORDS(2) }};

            // --- Heitz 2019: triangular-basis hash ---
            // Hash function maps tile index → random float2 in [0,1]^2
            float2 StochasticHash(float2 p, float seed)
            {{
                p = float2(dot(p, float2(127.1 + seed, 311.7)),
                           dot(p, float2(269.5 + seed, 183.3)));
                return frac(sin(p) * 43758.5453123);
            }}

            // Rotate UV by angle (radians) around center 0.5
            float2 RotateUV(float2 uv, float angle)
            {{
                float s = sin(angle), c = cos(angle);
                uv -= 0.5;
                uv = float2(c * uv.x - s * uv.y, s * uv.x + c * uv.y);
                return uv + 0.5;
            }}

            // Histogram-preserving blend: Gaussian to uniform CDF transform
            // Applied as a contrast correction to preserve texture luminance.
            float4 HistogramPreservingBlend(float4 c0, float4 c1, float4 c2, float3 w, float contrast)
            {{
                // Weighted blend
                float4 blended = c0 * w.x + c1 * w.y + c2 * w.z;
                // Contrast correction: expand toward mean to counteract
                // the variance compression of weighted averaging.
                // correction = mean + (blended - mean) * contrast_scale
                float4 mean = (c0 + c1 + c2) / 3.0;
                return mean + (blended - mean) * contrast;
            }}

            // --- Main stochastic sampler ---
            // Tiles the texture stochastically using 3 overlapping samples
            // at triangular-basis weights (Heitz 2019 Eq. 8).
            float4 SampleStochastic(TEXTURE2D_PARAM(tex, smp), float2 uv,
                                    float seed, float sharpness,
                                    float strength, float rotRange, float contrast)
            {{
                // Tile index and fractional position within tile
                float2 tileIdx = floor(uv);
                float2 fracUV  = frac(uv);

                // Triangular basis: 3 candidate tiles
                float2 h0 = StochasticHash(tileIdx,                  seed);
                float2 h1 = StochasticHash(tileIdx + float2(1, 0),   seed);
                float2 h2 = StochasticHash(tileIdx + float2(0, 1),   seed);

                // Per-tile UV offsets in [-0.5, 0.5] scaled by strength
                float2 o0 = (h0 - 0.5) * strength;
                float2 o1 = (h1 - 0.5) * strength;
                float2 o2 = (h2 - 0.5) * strength;

                // Per-tile rotation angles in [-rotRange/2, rotRange/2]
                float r0 = (h0.x - 0.5) * rotRange;
                float r1 = (h1.x - 0.5) * rotRange;
                float r2 = (h2.x - 0.5) * rotRange;

                // Triangular blend weights (smooth, sum-to-1 partition of unity)
                float3 w = float3(fracUV.x, fracUV.y, 1.0 - fracUV.x - fracUV.y);
                w = pow(saturate(w * sharpness), 2.0);
                w /= (w.x + w.y + w.z + 1e-6);

                // Sample texture at 3 offset+rotated UVs
                float4 c0 = SAMPLE_TEXTURE2D(tex, smp, RotateUV(uv + o0, r0));
                float4 c1 = SAMPLE_TEXTURE2D(tex, smp, RotateUV(uv + o1, r1));
                float4 c2 = SAMPLE_TEXTURE2D(tex, smp, RotateUV(uv + o2, r2));

                return HistogramPreservingBlend(c0, c1, c2, w, contrast);
            }}

            Varyings vert(Attributes IN)
            {{
                Varyings OUT;
                OUT.positionHCS = TransformObjectToHClip(IN.positionOS.xyz);
                OUT.uv = TRANSFORM_TEX(IN.uv, _BaseMap);
                OUT.normalWS = TransformObjectToWorldNormal(IN.normalOS);
                UNITY_TRANSFER_FOG(OUT, OUT.positionHCS);
                return OUT;
            }}

            half4 frag(Varyings IN) : SV_Target
            {{
                float2 uv = IN.uv * _TileSize;

                float4 albedo   = SampleStochastic(TEXTURE2D_ARGS(_BaseMap,         sampler_BaseMap),
                                                   uv, _StochasticSeed, _BlendSharpness,
                                                   _RandomnessStrength, _UVRotationRange,
                                                   _ContrastCorrection);
                float4 metallic = SampleStochastic(TEXTURE2D_ARGS(_MetallicGlossMap,sampler_MetallicGlossMap),
                                                   uv, _StochasticSeed + 1.0, _BlendSharpness,
                                                   _RandomnessStrength, _UVRotationRange,
                                                   _ContrastCorrection);
                float  ao       = SampleStochastic(TEXTURE2D_ARGS(_OcclusionMap,    sampler_OcclusionMap),
                                                   uv, _StochasticSeed + 2.0, _BlendSharpness,
                                                   _RandomnessStrength, _UVRotationRange,
                                                   _ContrastCorrection).r;

                InputData inputData = (InputData)0;
                inputData.normalWS = normalize(IN.normalWS);
                inputData.viewDirectionWS = GetWorldSpaceNormalizeViewDir(
                    TransformHClipToWorld(IN.positionHCS));

                SurfaceData surfaceData = (SurfaceData)0;
                surfaceData.albedo           = albedo.rgb;
                surfaceData.metallic         = metallic.r;
                surfaceData.smoothness       = metallic.a;
                surfaceData.occlusion        = ao;
                surfaceData.alpha            = 1.0;

                half4 color = UniversalFragmentPBR(inputData, surfaceData);
                UNITY_APPLY_FOG(IN.fogCoord, color);
                return color;
            }}
            ENDHLSL
        }}
    }}
    FallBack "Hidden/Universal Render Pipeline/FallbackError"
}}
"""


# ---------------------------------------------------------------------------
# Mikkelsen 2022 JCGT hex-tiling shader template
# "Practical Stochastic Sampling with Hexagonal Tiling" — JCGT Vol. 11 No. 3
# ---------------------------------------------------------------------------
_HLSL_HEX_STOCHASTIC_SHADER = r"""// VeilBreakers Terrain — Stochastic Hex-Tiling Shader
// Based on: Mikkelsen 2022 "Practical Stochastic Sampling with Hexagonal Tiling"
// JCGT Vol. 11 No. 3 — https://jcgt.org/published/0011/03/05/
// Auto-generated by terrain_stochastic_shader.py — do not edit manually.

Shader "VeilBreakers/TerrainLit_HexStochastic_{TEMPLATE_ID}"
{{
    Properties
    {{
        _BaseMap           ("Albedo",            2D)    = "white" {{}}
        _BumpMap           ("Normal Map",        2D)    = "bump"  {{}}
        _MetallicGlossMap  ("Metallic/Smoothness",2D)   = "white" {{}}
        _OcclusionMap      ("Occlusion",         2D)    = "white" {{}}
        _StochasticSeed    ("Stochastic Seed",   Float) = {STOCHASTIC_SEED}
        _BlendSharpness    ("Blend Sharpness",   Float) = {BLEND_SHARPNESS}
        _RandomnessStrength("Randomness Strength",Float)= {RANDOMNESS_STRENGTH}
        _TileSize          ("Tile Size (m)",     Float) = {TILE_SIZE}
        _ContrastCorrection("Contrast Correction",Float)= {CONTRAST_CORRECTION}
        _UVRotationRange   ("UV Rotation Range", Float) = {UV_ROTATION_RANGE}
    }}

    SubShader
    {{
        Tags {{ "RenderType"="Opaque" "RenderPipeline"="UniversalRenderPipeline" }}
        LOD 300

        Pass
        {{
            Name "ForwardLit"
            Tags {{ "LightMode"="UniversalForward" }}

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_fog
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            TEXTURE2D(_BaseMap);          SAMPLER(sampler_BaseMap);
            TEXTURE2D(_BumpMap);          SAMPLER(sampler_BumpMap);
            TEXTURE2D(_MetallicGlossMap); SAMPLER(sampler_MetallicGlossMap);
            TEXTURE2D(_OcclusionMap);     SAMPLER(sampler_OcclusionMap);

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseMap_ST;
                float  _StochasticSeed;
                float  _BlendSharpness;
                float  _RandomnessStrength;
                float  _TileSize;
                float  _ContrastCorrection;
                float  _UVRotationRange;
            CBUFFER_END

            struct Attributes {{ float4 positionOS : POSITION; float2 uv : TEXCOORD0; float3 normalOS : NORMAL; }};
            struct Varyings   {{ float4 positionHCS : SV_POSITION; float2 uv : TEXCOORD0; float3 normalWS : TEXCOORD1; UNITY_FOG_COORDS(2) }};

            // --- Shared helpers (identical to triangular variant) ---
            float2 StochasticHash(float2 p, float seed)
            {{
                p = float2(dot(p, float2(127.1 + seed, 311.7)),
                           dot(p, float2(269.5 + seed, 183.3)));
                return frac(sin(p) * 43758.5453123);
            }}

            float2 RotateUV(float2 uv, float angle)
            {{
                float s = sin(angle), c = cos(angle);
                uv -= 0.5;
                uv = float2(c * uv.x - s * uv.y, s * uv.x + c * uv.y);
                return uv + 0.5;
            }}

            float4 HistogramPreservingBlend(float4 c0, float4 c1, float4 c2, float3 w, float contrast)
            {{
                float4 blended = c0 * w.x + c1 * w.y + c2 * w.z;
                float4 mean = (c0 + c1 + c2) / 3.0;
                return mean + (blended - mean) * contrast;
            }}

            // --- Mikkelsen 2022 hex-tiling coordinate decomposition ---
            // Rect-to-hex and hex-to-rect transforms for a 60° hex grid.
            // kRectToHex maps world UV → hex fractional, kHexToRect maps back.
            static const float2x2 kRectToHex = float2x2(1.0, -0.57735027, 0.0, 1.15470054);
            static const float2x2 kHexToRect = float2x2(1.0,  0.5,        0.0, 0.86602540);

            void HexCoords(float2 uv, out float2 h1, out float2 h2, out float2 h3, out float3 w)
            {{
                float2 hp = mul(kRectToHex, uv);
                float2 ip = floor(hp);
                float2 fp = fp = hp - ip;

                // Partition each hex rhombus into two triangles.
                // The point falls in one triangle; its 3 surrounding hex centers
                // are the 3 blend candidates (Mikkelsen 2022 Section 3).
                if (fp.x + fp.y < 1.0)
                {{
                    h1 = ip;
                    h2 = ip + float2(1.0, 0.0);
                    h3 = ip + float2(0.0, 1.0);
                    w  = float3(1.0 - fp.x - fp.y, fp.x, fp.y);
                }}
                else
                {{
                    h1 = ip + float2(1.0, 1.0);
                    h2 = ip + float2(0.0, 1.0);
                    h3 = ip + float2(1.0, 0.0);
                    w  = float3(fp.x + fp.y - 1.0, 1.0 - fp.x, 1.0 - fp.y);
                }}

                // Power-4 smooth weighting gives seamless hex blending
                // (Mikkelsen 2022 Eq. 7 — exponent 4 minimises seam visibility).
                w = pow(saturate(w), 4.0);
                w /= (w.x + w.y + w.z + 1e-6);

                // Transform hex centers back to UV space for offset sampling.
                h1 = mul(kHexToRect, h1);
                h2 = mul(kHexToRect, h2);
                h3 = mul(kHexToRect, h3);
            }}

            float4 SampleHexStochastic(TEXTURE2D_PARAM(tex, smp), float2 uv,
                                       float seed, float strength,
                                       float rotRange, float contrast)
            {{
                float2 h1, h2, h3;
                float3 w;
                HexCoords(uv, h1, h2, h3, w);

                float2 rand1 = StochasticHash(h1, seed);
                float2 rand2 = StochasticHash(h2, seed);
                float2 rand3 = StochasticHash(h3, seed);

                float2 o1 = (rand1 - 0.5) * strength;
                float2 o2 = (rand2 - 0.5) * strength;
                float2 o3 = (rand3 - 0.5) * strength;

                float r1 = (rand1.x - 0.5) * rotRange;
                float r2 = (rand2.x - 0.5) * rotRange;
                float r3 = (rand3.x - 0.5) * rotRange;

                float4 c1 = SAMPLE_TEXTURE2D(tex, smp, RotateUV(uv + o1, r1));
                float4 c2 = SAMPLE_TEXTURE2D(tex, smp, RotateUV(uv + o2, r2));
                float4 c3 = SAMPLE_TEXTURE2D(tex, smp, RotateUV(uv + o3, r3));

                return HistogramPreservingBlend(c1, c2, c3, w, contrast);
            }}

            Varyings vert(Attributes IN)
            {{
                Varyings OUT;
                OUT.positionHCS = TransformObjectToHClip(IN.positionOS.xyz);
                OUT.uv = TRANSFORM_TEX(IN.uv, _BaseMap);
                OUT.normalWS = TransformObjectToWorldNormal(IN.normalOS);
                UNITY_TRANSFER_FOG(OUT, OUT.positionHCS);
                return OUT;
            }}

            half4 frag(Varyings IN) : SV_Target
            {{
                float2 uv = IN.uv * _TileSize;

                float4 albedo   = SampleHexStochastic(TEXTURE2D_ARGS(_BaseMap,         sampler_BaseMap),
                                                      uv, _StochasticSeed, _RandomnessStrength,
                                                      _UVRotationRange, _ContrastCorrection);
                float4 metallic = SampleHexStochastic(TEXTURE2D_ARGS(_MetallicGlossMap,sampler_MetallicGlossMap),
                                                      uv, _StochasticSeed + 1.0, _RandomnessStrength,
                                                      _UVRotationRange, _ContrastCorrection);
                float  ao       = SampleHexStochastic(TEXTURE2D_ARGS(_OcclusionMap,    sampler_OcclusionMap),
                                                      uv, _StochasticSeed + 2.0, _RandomnessStrength,
                                                      _UVRotationRange, _ContrastCorrection).r;

                InputData inputData = (InputData)0;
                inputData.normalWS = normalize(IN.normalWS);
                inputData.viewDirectionWS = GetWorldSpaceNormalizeViewDir(
                    TransformHClipToWorld(IN.positionHCS));

                SurfaceData surfaceData = (SurfaceData)0;
                surfaceData.albedo           = albedo.rgb;
                surfaceData.metallic         = metallic.r;
                surfaceData.smoothness       = metallic.a;
                surfaceData.occlusion        = ao;
                surfaceData.alpha            = 1.0;

                half4 color = UniversalFragmentPBR(inputData, surfaceData);
                UNITY_APPLY_FOG(IN.fogCoord, color);
                return color;
            }}
            ENDHLSL
        }}
    }}
    FallBack "Hidden/Universal Render Pipeline/FallbackError"
}}
"""


@dataclass
class StochasticShaderTemplate:
    """Parameters describing a Heitz 2019 / Mikkelsen 2022 stochastic shader.

    Set ``tiling_mode="hex"`` to emit the Mikkelsen 2022 JCGT hex-tiling
    shader instead of the default Heitz 2019 triangular-basis variant.
    Hex-tiling eliminates the faint grid artifact visible in the triangular
    approach on low-frequency textures (e.g. sand, snow, mud).

    All fields are consumed by both the Python UV-offset bake
    (``build_stochastic_sampling_mask``) and the Unity HLSL shader template
    (``export_unity_shader_template``).

    Fields
    ------
    template_id : str
        Unique identifier embedded in the shader name.
    tile_size_m : float
        World-space size of one texture tile in metres.
    randomness_strength : float
        Per-tile UV offset scale in [0, 1].  0 = pure tiling (no breakup),
        1 = maximum Heitz-Neyret offset.
    histogram_preserving : bool
        If True, apply rank-based histogram equalisation to the UV offset
        channels so the output distribution is uniform across [-0.5, 0.5].
        This prevents the brightness drift caused by bilinear interpolation
        compressing offsets toward zero.
    contrast_correction : float
        Contrast expansion factor applied during histogram-preserving blend
        (Heitz 2019 Eq. 10).  Values > 1 expand contrast; 1.0 = identity.
        Typical range: 1.0–2.0.
    uv_rotation_range : float
        Maximum per-tile UV rotation in radians.  Rotated samples break up
        directional repetition artifacts (e.g. oriented rock grain).
        0.0 disables rotation; math.pi/4 (45°) is a typical AAA value.
    layer_index : int
        Which terrain layer index this template governs.
    notes : str
        Free-form human-readable notes.
    stochastic_seed : int
        Hash seed fed to the per-tile RNG in the HLSL shader.
    blend_sharpness : float
        Exponent of the triangular-basis blend kernel (Heitz 2019 Eq. 8).
        Higher values create sharper tile boundaries; 2.0 is the standard.
    blend_weights : List[float]
        Per-sample blend weights; must sum to 1.0.
    """

    template_id: str
    tile_size_m: float = 4.0
    randomness_strength: float = 0.75
    histogram_preserving: bool = True
    contrast_correction: float = 1.4
    uv_rotation_range: float = 0.0
    layer_index: int = 0
    notes: str = ""
    stochastic_seed: int = 0
    blend_sharpness: float = 2.0
    blend_weights: List[float] = field(default_factory=lambda: [1.0])
    tiling_mode: str = "triangular"  # "triangular" = Heitz 2019; "hex" = Mikkelsen 2022 JCGT

    _VALID_TILING_MODES = frozenset({"triangular", "hex"})

    def __post_init__(self) -> None:
        if self.tile_size_m <= 0.0:
            raise ValueError(f"tile_size_m must be > 0, got {self.tile_size_m}")
        if not (0.0 <= self.randomness_strength <= 1.0):
            raise ValueError(
                f"randomness_strength must be in [0, 1], got {self.randomness_strength}"
            )
        if self.blend_sharpness <= 0.0:
            raise ValueError(f"blend_sharpness must be > 0, got {self.blend_sharpness}")
        if self.contrast_correction <= 0.0:
            raise ValueError(f"contrast_correction must be > 0, got {self.contrast_correction}")
        if self.uv_rotation_range < 0.0:
            raise ValueError(f"uv_rotation_range must be >= 0, got {self.uv_rotation_range}")
        if not self.blend_weights:
            raise ValueError("blend_weights must be a non-empty list")
        total = sum(self.blend_weights)
        if abs(total - 1.0) > 1e-4:
            raise ValueError(
                f"blend_weights must sum to 1.0, got sum={total:.6f}"
            )
        if self.tiling_mode not in self._VALID_TILING_MODES:
            raise ValueError(
                f"tiling_mode must be one of {sorted(self._VALID_TILING_MODES)}, "
                f"got {self.tiling_mode!r}"
            )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "template_id": self.template_id,
            "tile_size_m": float(self.tile_size_m),
            "randomness_strength": float(self.randomness_strength),
            "histogram_preserving": bool(self.histogram_preserving),
            "contrast_correction": float(self.contrast_correction),
            "uv_rotation_range": float(self.uv_rotation_range),
            "layer_index": int(self.layer_index),
            "notes": self.notes,
            "stochastic_seed": int(self.stochastic_seed),
            "blend_sharpness": float(self.blend_sharpness),
            "blend_weights": [float(w) for w in self.blend_weights],
            "tiling_mode": self.tiling_mode,
        }


def _tile_hash_2d(tile_y: np.ndarray, tile_x: np.ndarray, seed: int) -> np.ndarray:
    """Hash (tile_y, tile_x) integer grid indices to a (N, 4) float32 array in [0,1].

    Uses a fast integer hash (Murmur3-inspired) that maps each (ty, tx) pair
    to 4 independent pseudo-random floats:
      col 0: u-offset channel
      col 1: v-offset channel
      col 2: rotation channel
      col 3: spare (contrast jitter, reserved)

    All four channels are independent.  Output is deterministic for fixed inputs.
    """
    # Flatten and pack into a single uint32 for hashing
    s = np.uint32(int(seed) & 0xFFFFFFFF)
    ty = tile_y.ravel().astype(np.uint32)
    tx = tile_x.ravel().astype(np.uint32)
    n = ty.size

    # Murmur3-inspired integer hash — four independent seeds per tile
    def _hash(a: np.ndarray, b: np.ndarray, k: np.uint32) -> np.ndarray:
        h = (a * np.uint32(2654435761)) ^ (b * np.uint32(2246822519)) ^ (s ^ k)
        h ^= h >> np.uint32(16)
        h *= np.uint32(0x45D9F3B)
        h ^= h >> np.uint32(16)
        return h.astype(np.float32) / np.float32(2 ** 32)

    out = np.empty((n, 4), dtype=np.float32)
    out[:, 0] = _hash(ty, tx, np.uint32(0))
    out[:, 1] = _hash(ty, tx, np.uint32(1))
    out[:, 2] = _hash(ty, tx, np.uint32(2))
    out[:, 3] = _hash(ty, tx, np.uint32(3))
    return out


def build_stochastic_sampling_mask(
    stack: TerrainMaskStack,
    tile_size_m: float,
    seed: int,
    coverage_fraction: float = 0.5,
    use_voronoi: bool = False,
    histogram_preserving: bool = True,
    uv_rotation_range: float = 0.0,
) -> np.ndarray:
    """Return a (H, W, 2) float32 UV-offset mask using Heitz 2019 per-tile hashing.

    Implementation follows Heitz & Neyret 2019 "Histogram-Preserving Blending":

    1. Divide the heightmap into a grid of texture tiles.
    2. For each tile cell, compute a deterministic hash → (u_offset, v_offset,
       rotation_angle) using a Murmur3-inspired integer hash of (tile_y, tile_x).
       This is the true Heitz/Neyret approach: hash-based per-tile random offsets
       rather than noise-based, giving perfectly uniform coverage with no
       spatial bias.
    3. Assign each heightmap pixel to its tile cell and look up the tile's offset.
    4. Apply UV rotation per tile (optional): rotate the UV offset vector by the
       tile's random rotation angle, breaking directional repetition in oriented
       textures such as rock grain and wood.
    5. If ``histogram_preserving=True``, apply rank-based equalisation to each
       channel so the output distribution is exactly uniform in [-0.5, 0.5],
       correcting the bilinear pull-toward-zero bias.

    Strategy B (``use_voronoi=True``):
      Same hash-based offsets but tile boundaries are hard (nearest-tile
      assignment, no interpolation), matching UE5's Voronoi stochastic node.

    Parameters
    ----------
    stack : TerrainMaskStack
        Must have ``height`` populated (shape/cell_size only).
    tile_size_m : float
        World-space size of one tileable texture tile in metres.
    seed : int
        Deterministic seed.
    coverage_fraction : float
        Unused in hash path; kept for API compatibility with fBm callers.
    use_voronoi : bool
        Hard-cell tile boundaries (no bilinear blend between tiles).
    histogram_preserving : bool
        Apply rank-based equalisation to UV channels.  Default True.
    uv_rotation_range : float
        Maximum per-tile rotation in radians (symmetric around 0).
        0.0 disables rotation.

    Returns
    -------
    np.ndarray
        Shape (H, W, 2), dtype float32.
        Channel 0 = U offset in [-0.5, 0.5].
        Channel 1 = V offset in [-0.5, 0.5].
    """
    if stack.height is None:
        raise ValueError("build_stochastic_sampling_mask requires stack.height")
    if tile_size_m <= 0.0:
        raise ValueError(f"tile_size_m must be > 0, got {tile_size_m}")
    if not (0.0 < coverage_fraction <= 1.0):
        raise ValueError(f"coverage_fraction must be in (0, 1], got {coverage_fraction}")

    h_arr = np.asarray(stack.height)
    rows, cols = h_arr.shape
    cell_m = float(stack.cell_size)

    # --- Per-pixel tile-index assignment -----------------------------------
    # Each pixel maps to a tile cell index (ty, tx).
    row_tile_f = np.arange(rows, dtype=np.float64) * cell_m / tile_size_m
    col_tile_f = np.arange(cols, dtype=np.float64) * cell_m / tile_size_m

    row_tile_idx = np.floor(row_tile_f).astype(np.int32)
    col_tile_idx = np.floor(col_tile_f).astype(np.int32)

    tiles_y = int(row_tile_idx.max()) + 2
    tiles_x = int(col_tile_idx.max()) + 2
    row_tile_idx = np.clip(row_tile_idx, 0, tiles_y - 1)
    col_tile_idx = np.clip(col_tile_idx, 0, tiles_x - 1)

    # --- Build hash table for every tile cell ----------------------------
    # Shape: (tiles_y * tiles_x, 4)
    ty_grid, tx_grid = np.mgrid[0:tiles_y, 0:tiles_x]
    hash_vals = _tile_hash_2d(ty_grid.ravel(), tx_grid.ravel(), int(seed) & 0xFFFFFFFF)
    # Reshape to (tiles_y, tiles_x, 4)
    hash_grid = hash_vals.reshape(tiles_y, tiles_x, 4)

    # UV offsets: map [0,1] hash → [-0.5, 0.5]
    tile_u = (hash_grid[..., 0] - 0.5).astype(np.float32)
    tile_v = (hash_grid[..., 1] - 0.5).astype(np.float32)
    tile_r = (hash_grid[..., 2] - 0.5).astype(np.float32) * float(uv_rotation_range)

    if use_voronoi:
        # Hard-cell: each pixel gets the exact offset of its owning tile
        u = tile_u[np.ix_(row_tile_idx, col_tile_idx)]
        v = tile_v[np.ix_(row_tile_idx, col_tile_idx)]
        rot = tile_r[np.ix_(row_tile_idx, col_tile_idx)] if uv_rotation_range > 0 else None
    else:
        # Smooth: bilinearly interpolate between tile corners for continuity
        ty_f = row_tile_f - row_tile_idx.astype(np.float64)   # frac in [0,1)
        tx_f = col_tile_f - col_tile_idx.astype(np.float64)

        y0 = row_tile_idx
        x0 = col_tile_idx
        y1 = np.clip(y0 + 1, 0, tiles_y - 1)
        x1 = np.clip(x0 + 1, 0, tiles_x - 1)
        wy = ty_f.reshape(-1, 1).astype(np.float32)
        wx = tx_f.reshape(1, -1).astype(np.float32)

        def _bilerp(g: np.ndarray) -> np.ndarray:
            a = g[np.ix_(y0, x0)]
            b = g[np.ix_(y0, x1)]
            c = g[np.ix_(y1, x0)]
            d = g[np.ix_(y1, x1)]
            return (a * (1 - wx) + b * wx) * (1 - wy) + (c * (1 - wx) + d * wx) * wy

        u = _bilerp(tile_u)
        v = _bilerp(tile_v)
        rot = _bilerp(tile_r) if uv_rotation_range > 0 else None

    # --- UV rotation: rotate (u, v) by per-tile angle -------------------
    if rot is not None:
        cos_r = np.cos(rot).astype(np.float32)
        sin_r = np.sin(rot).astype(np.float32)
        u_rot = cos_r * u - sin_r * v
        v_rot = sin_r * u + cos_r * v
        u = u_rot
        v = v_rot

    result = np.stack([u, v], axis=-1).astype(np.float32)

    # --- Histogram-preserving equalisation (Heitz 2019 Eq. 10) ----------
    # Rank-remap each channel to a uniform distribution in [-0.5, 0.5].
    # This corrects the bilinear pull-toward-zero that would otherwise cause
    # visible brightness drift in tiled PBR textures.
    if histogram_preserving:
        for ch in range(2):
            chan = result[..., ch].ravel()
            n = chan.size
            rank = np.empty(n, dtype=np.float32)
            order = np.argsort(chan)
            rank[order] = np.linspace(-0.5, 0.5, n, dtype=np.float32)
            result[..., ch] = rank.reshape(result.shape[:2])

    return result


# ---------------------------------------------------------------------------
# Mikkelsen 2022 JCGT — hex-tiling UV offset mask (Python bake path)
# ---------------------------------------------------------------------------

def build_hex_tiling_mask(
    stack: "TerrainMaskStack",
    tile_size_m: float,
    seed: int,
    histogram_preserving: bool = True,
    uv_rotation_range: float = 0.0,
) -> np.ndarray:
    """Return a (H, W, 2) float32 UV-offset mask using Mikkelsen 2022 hex-tiling.

    Implements the Python CPU-bake equivalent of the hex HLSL shader (Section 3
    of Mikkelsen 2022 JCGT Vol. 11 No. 3).  Each texel gets the blend-weighted
    average UV offset of its three surrounding hex centers, removing the faint
    axis-aligned grid artifact produced by the triangular Heitz 2019 approach.

    The hex lattice uses a 60°-skewed coordinate system:
      RectToHex = [[1, -1/√3], [0, 2/√3]]
      HexToRect = [[1, 1/2],   [0, √3/2]]

    For each pixel p in UV space:
      1. hp = RectToHex · (p / tile_size_m)
      2. ip = floor(hp);  fp = hp - ip
      3. Two triangle candidates (fp.x + fp.y < 1 or ≥ 1)
      4. w = pow4 smooth weights → normalised
      5. offset = weighted average of hash offsets at 3 hex centers

    Parameters
    ----------
    stack : TerrainMaskStack
        Must have ``height`` populated (shape / cell_size only).
    tile_size_m : float
        World-space size of one tileable texture tile in metres.
    seed : int
        Deterministic seed.
    histogram_preserving : bool
        Rank-equalise each channel to a uniform distribution in [-0.5, 0.5].
    uv_rotation_range : float
        Maximum per-tile rotation in radians (0 = no rotation).

    Returns
    -------
    np.ndarray  shape (H, W, 2), dtype float32.
        Channel 0 = U offset in [-0.5, 0.5].
        Channel 1 = V offset in [-0.5, 0.5].
    """
    import math as _math

    if stack.height is None:
        raise ValueError("build_hex_tiling_mask requires stack.height")
    if tile_size_m <= 0.0:
        raise ValueError(f"tile_size_m must be > 0, got {tile_size_m}")

    h_arr = np.asarray(stack.height)
    rows, cols = h_arr.shape
    cell_m = float(stack.cell_size)

    # World-space UV coordinates for each pixel (tile-normalised)
    pu = np.arange(cols, dtype=np.float32) * cell_m / tile_size_m   # (W,)
    pv = np.arange(rows, dtype=np.float32) * cell_m / tile_size_m   # (H,)

    # Hex transform: RectToHex = [[1, -1/sqrt(3)], [0, 2/sqrt(3)]]
    inv_sqrt3 = np.float32(1.0 / _math.sqrt(3.0))
    two_over_sqrt3 = np.float32(2.0 / _math.sqrt(3.0))

    # hp = RectToHex @ [u, v]:  hp_u = u - v/sqrt(3);  hp_v = v * 2/sqrt(3)
    pu_g, pv_g = np.meshgrid(pu, pv)  # both (H, W)
    hp_u = pu_g - pv_g * inv_sqrt3
    hp_v = pv_g * two_over_sqrt3

    # Integer hex cell and fractional position
    ip_u = np.floor(hp_u).astype(np.int32)
    ip_v = np.floor(hp_v).astype(np.int32)
    fp_u = (hp_u - ip_u).astype(np.float32)
    fp_v = (hp_v - ip_v).astype(np.float32)

    # HexToRect = [[1, 0.5], [0, sqrt(3)/2]]
    half = np.float32(0.5)
    sqrt3_over2 = np.float32(_math.sqrt(3.0) / 2.0)

    def _hex_to_rect_u(hu: np.ndarray, hv: np.ndarray) -> np.ndarray:
        return hu.astype(np.float32) + hv.astype(np.float32) * half

    def _hex_to_rect_v(hv: np.ndarray) -> np.ndarray:
        return hv.astype(np.float32) * sqrt3_over2

    # Murmur3-inspired float hash for 2D hex center → (u_off, v_off, rot)
    s = np.uint32(int(seed) & 0xFFFFFFFF)

    def _hash_hex(hu: np.ndarray, hv: np.ndarray, k: np.uint32) -> np.ndarray:
        a = hu.ravel().astype(np.int32).view(np.uint32)
        b = hv.ravel().astype(np.int32).view(np.uint32)
        h = (a * np.uint32(2654435761)) ^ (b * np.uint32(2246822519)) ^ (s ^ k)
        h ^= h >> np.uint32(16)
        h *= np.uint32(0x45D9F3B)
        h ^= h >> np.uint32(16)
        return (h.astype(np.float64) / float(2 ** 32)).reshape(hu.shape).astype(np.float32)

    # Determine triangle case per pixel (vectorised)
    case_hi = (fp_u + fp_v) >= 1.0  # True = upper triangle

    # Hex center indices for the 3 candidates (each (H,W))
    h1u = np.where(case_hi, ip_u + 1, ip_u).astype(np.int32)
    h1v = np.where(case_hi, ip_v + 1, ip_v).astype(np.int32)
    h2u = ip_u.astype(np.int32)
    h2v = (ip_v + 1).astype(np.int32)
    h3u = (ip_u + 1).astype(np.int32)
    h3v = ip_v.astype(np.int32)

    # Blend weights (power-4 smooth, normalised)
    w1 = np.where(case_hi, fp_u + fp_v - 1.0, 1.0 - fp_u - fp_v).astype(np.float32)
    w2 = np.where(case_hi, 1.0 - fp_u, fp_v).astype(np.float32)
    w3 = np.where(case_hi, 1.0 - fp_v, fp_u).astype(np.float32)
    w1 = np.clip(w1, 0.0, 1.0) ** 4
    w2 = np.clip(w2, 0.0, 1.0) ** 4
    w3 = np.clip(w3, 0.0, 1.0) ** 4
    w_sum = w1 + w2 + w3 + np.float32(1e-6)
    w1 /= w_sum
    w2 /= w_sum
    w3 /= w_sum

    # Per-hex-center hash offsets in [-0.5, 0.5]
    ou1 = _hash_hex(h1u, h1v, np.uint32(0)) - 0.5
    ov1 = _hash_hex(h1u, h1v, np.uint32(1)) - 0.5
    ou2 = _hash_hex(h2u, h2v, np.uint32(0)) - 0.5
    ov2 = _hash_hex(h2u, h2v, np.uint32(1)) - 0.5
    ou3 = _hash_hex(h3u, h3v, np.uint32(0)) - 0.5
    ov3 = _hash_hex(h3u, h3v, np.uint32(1)) - 0.5

    # Weighted blend of offsets
    u = w1 * ou1 + w2 * ou2 + w3 * ou3
    v = w1 * ov1 + w2 * ov2 + w3 * ov3

    # Optional UV rotation (blend-weighted angle)
    if uv_rotation_range > 0.0:
        r1 = (_hash_hex(h1u, h1v, np.uint32(2)) - 0.5) * float(uv_rotation_range)
        r2 = (_hash_hex(h2u, h2v, np.uint32(2)) - 0.5) * float(uv_rotation_range)
        r3 = (_hash_hex(h3u, h3v, np.uint32(2)) - 0.5) * float(uv_rotation_range)
        rot = (w1 * r1 + w2 * r2 + w3 * r3).astype(np.float32)
        cos_r = np.cos(rot).astype(np.float32)
        sin_r = np.sin(rot).astype(np.float32)
        u_rot = cos_r * u - sin_r * v
        v_rot = sin_r * u + cos_r * v
        u, v = u_rot, v_rot

    result = np.stack([u, v], axis=-1).astype(np.float32)

    if histogram_preserving:
        for ch in range(2):
            chan = result[..., ch].ravel()
            n = chan.size
            rank = np.empty(n, dtype=np.float32)
            order = np.argsort(chan)
            rank[order] = np.linspace(-0.5, 0.5, n, dtype=np.float32)
            result[..., ch] = rank.reshape(result.shape[:2])

    return result


# ---------------------------------------------------------------------------
# Required Unity shader properties (validated on export)
# ---------------------------------------------------------------------------

_REQUIRED_UNITY_SHADER_PROPERTIES = {
    "_BaseMap",
    "_BumpMap",
    "_MetallicGlossMap",
    "_OcclusionMap",
    "_StochasticSeed",
    "_BlendSharpness",
    "_RandomnessStrength",
    "_TileSize",
    "_ContrastCorrection",
    "_UVRotationRange",
}


def export_unity_shader_template(
    template: StochasticShaderTemplate,
    output_path: Path,
) -> Dict[str, Any]:
    """Emit a valid Unity shader asset for the stochastic template.

    Writes two files side-by-side:
      ``<output_path>.shader`` — complete HLSL Unity shader (Heitz 2019
          triangular-basis stochastic sampling, histogram-preserving blend,
          contrast correction, per-tile UV rotation).
      ``<output_path>``        — JSON manifest (schema-v1) consumed by the
          Unity-side terrain importer.

    Both files share the same stem; the .shader suffix is added automatically
    when the output path does not already end with ``.shader``.

    All required Unity shader property names are validated before writing.

    Returns the JSON manifest dict so callers can inspect without re-reading.

    Raises
    ------
    ValueError
        If any required Unity shader property is absent from the manifest.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    tpl = template.to_dict()

    # --- HLSL shader file -----------------------------------------------
    # Select triangular (Heitz 2019) or hex (Mikkelsen 2022) template.
    shader_path = output_path.with_suffix(".shader")
    hlsl_tpl = (
        _HLSL_HEX_STOCHASTIC_SHADER
        if tpl.get("tiling_mode") == "hex"
        else _HLSL_STOCHASTIC_SHADER
    )
    hlsl_code = hlsl_tpl.format(
        TEMPLATE_ID=tpl["template_id"],
        STOCHASTIC_SEED=tpl["stochastic_seed"],
        BLEND_SHARPNESS=tpl["blend_sharpness"],
        RANDOMNESS_STRENGTH=tpl["randomness_strength"],
        TILE_SIZE=tpl["tile_size_m"],
        CONTRAST_CORRECTION=tpl["contrast_correction"],
        UV_ROTATION_RANGE=tpl["uv_rotation_range"],
    )
    shader_path.write_text(hlsl_code, encoding="utf-8")

    # --- JSON manifest --------------------------------------------------
    properties: Dict[str, Any] = {
        "_BaseMap":            {"type": "Texture2D", "default": "white"},
        "_BumpMap":            {"type": "Texture2D", "default": "bump"},
        "_MetallicGlossMap":   {"type": "Texture2D", "default": "white"},
        "_OcclusionMap":       {"type": "Texture2D", "default": "white"},
        "_StochasticSeed":     {"type": "Float", "default": tpl["stochastic_seed"]},
        "_BlendSharpness":     {"type": "Float", "default": tpl["blend_sharpness"]},
        "_RandomnessStrength": {"type": "Float", "default": tpl["randomness_strength"]},
        "_TileSize":           {"type": "Float", "default": tpl["tile_size_m"]},
        "_ContrastCorrection": {"type": "Float", "default": tpl["contrast_correction"]},
        "_UVRotationRange":    {"type": "Float", "default": tpl["uv_rotation_range"]},
    }

    stochastic_params: Dict[str, Any] = {
        "histogram_preserving": tpl["histogram_preserving"],
        "contrast_correction":  tpl["contrast_correction"],
        "uv_rotation_range":    tpl["uv_rotation_range"],
        "blend_weights":        tpl["blend_weights"],
        "layer_index":          tpl["layer_index"],
    }

    texture_channels: List[str] = ["Albedo", "Normal", "MetallicSmoothness", "AO"]

    payload: Dict[str, Any] = {
        "schema": "veilbreakers.terrain.stochastic_shader/v1",
        "shader_name": f"VeilBreakers/TerrainLit_Stochastic_{tpl['template_id']}",
        "shader_asset_path": str(shader_path),
        "shader_graph_type": "ShaderGraph/TerrainLit_Stochastic",
        "template": tpl,
        "properties": properties,
        "stochastic_params": stochastic_params,
        "texture_channels": texture_channels,
        "inputs": {
            "SamplingMask": "Texture2D_float2",
            "TileSize": "Float",
            "RandomnessStrength": "Float",
            "ContrastCorrection": "Float",
            "UVRotationRange": "Float",
        },
        "outputs": {
            "Albedo": "Vector3",
            "Roughness": "Float",
            "Normal": "Vector3",
            "Metallic": "Float",
            "AO": "Float",
        },
    }

    # Validate required Unity shader properties
    missing = _REQUIRED_UNITY_SHADER_PROPERTIES - set(payload["properties"].keys())
    if missing:
        raise ValueError(
            f"export_unity_shader_template: missing required Unity shader "
            f"properties: {sorted(missing)}"
        )

    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return payload


def pass_stochastic_shader(
    state: TerrainPipelineState,
    region: Optional[BBox],
) -> PassResult:
    """Bundle K pass: build Heitz 2019 stochastic UV mask, export shader, store on stack.

    Workflow
    --------
    1. Build per-tile hash UV offsets via ``build_stochastic_sampling_mask``
       (Heitz 2019 triangular-basis, histogram-preserving, optional rotation).
    2. Construct a ``StochasticShaderTemplate`` from hints.
    3. Export Unity .shader + JSON manifest if ``stochastic_shader_export_path``
       is set in composition_hints.
    4. Store ``stochastic_uv_mask`` (H, W, 2) and ``stochastic_offset_mask``
       (H, W) scalar magnitude on the stack.

    Consumes: height
    Produces: stochastic_uv_mask, stochastic_offset_mask
    roughness_variation is owned exclusively by terrain_roughness_driver (Fix 7.18).
    """
    from .terrain_pipeline import derive_pass_seed

    t0 = time.perf_counter()
    stack = state.mask_stack
    hints = state.intent.composition_hints if state.intent else {}

    tile_size_m = float(hints.get("stochastic_tile_size_m", 4.0))
    coverage_fraction = float(hints.get("stochastic_coverage_fraction", 0.5))
    use_voronoi = bool(hints.get("stochastic_use_voronoi", False))
    histogram_preserving = bool(hints.get("stochastic_histogram_preserving", True))
    uv_rotation_range = float(hints.get("stochastic_uv_rotation_range", 0.0))
    contrast_correction = float(hints.get("stochastic_contrast_correction", 1.4))
    blend_sharpness = float(hints.get("stochastic_blend_sharpness", 2.0))
    tiling_mode = str(hints.get("stochastic_tiling_mode", "triangular"))
    if tiling_mode not in StochasticShaderTemplate._VALID_TILING_MODES:
        logger.warning(
            "pass_stochastic_shader: unknown tiling_mode %r; falling back to 'triangular'",
            tiling_mode,
        )
        tiling_mode = "triangular"

    seed = derive_pass_seed(
        state.intent.seed if state.intent else 0,
        "stochastic_shader",
        state.tile_x,
        state.tile_y,
        region,
    )

    # Step 1: Build UV offset mask.
    # "hex" → Mikkelsen 2022 JCGT hex-tiling (better for low-frequency textures).
    # "triangular" → Heitz 2019 triangular-basis (default, well-tested).
    if tiling_mode == "hex":
        mask = build_hex_tiling_mask(
            stack,
            tile_size_m,
            seed,
            histogram_preserving=histogram_preserving,
            uv_rotation_range=uv_rotation_range,
        )
    else:
        mask = build_stochastic_sampling_mask(
            stack,
            tile_size_m,
            seed,
            coverage_fraction=coverage_fraction,
            use_voronoi=use_voronoi,
            histogram_preserving=histogram_preserving,
            uv_rotation_range=uv_rotation_range,
        )

    # Step 2: Build template dataclass
    tpl = StochasticShaderTemplate(
        template_id=str(hints.get("stochastic_template_id", f"layer{state.tile_x}_{state.tile_y}")),
        tile_size_m=tile_size_m,
        randomness_strength=float(hints.get("stochastic_randomness_strength", 0.75)),
        histogram_preserving=histogram_preserving,
        contrast_correction=contrast_correction,
        uv_rotation_range=uv_rotation_range,
        layer_index=int(hints.get("stochastic_layer_index", 0)),
        stochastic_seed=int(seed) & 0x7FFFFFFF,
        blend_sharpness=blend_sharpness,
        blend_weights=[1.0],
        tiling_mode=tiling_mode,
    )

    # Step 3: Export shader asset if path provided
    export_path_str = hints.get("stochastic_shader_export_path", "")
    exported_manifest: Optional[str] = None
    if export_path_str:
        export_path = Path(str(export_path_str))
        export_unity_shader_template(tpl, export_path)
        exported_manifest = str(export_path)

    # Step 4: Store stack channels
    stack.set("stochastic_uv_mask", mask, "stochastic_shader")

    # Compute offset magnitude for metrics (not stored on stack — TerrainMaskStack
    # does not declare stochastic_offset_mask as a channel; Fix 7.18 single-writer rule).
    offset_magnitude = np.sqrt(
        mask[..., 0].astype(np.float64) ** 2
        + mask[..., 1].astype(np.float64) ** 2
    ).astype(np.float32)

    # roughness_variation is written only by terrain_roughness_driver (Fix 7.18)

    metrics: dict = {
        "tile_size_m": tile_size_m,
        "coverage_fraction": coverage_fraction,
        "use_voronoi": use_voronoi,
        "histogram_preserving": histogram_preserving,
        "uv_rotation_range": uv_rotation_range,
        "contrast_correction": contrast_correction,
        "mask_shape": list(mask.shape),
        "offset_mean_abs": float(np.mean(np.abs(mask))),
        "offset_magnitude_mean": float(np.mean(offset_magnitude)),
        "seed_used": int(seed),
    }
    if exported_manifest:
        metrics["exported_manifest"] = exported_manifest

    return PassResult(
        pass_name="stochastic_shader",
        status="ok",
        duration_seconds=time.perf_counter() - t0,
        consumed_channels=("height",),
        produced_channels=("stochastic_uv_mask",),
        metrics=metrics,
        issues=[],
        seed_used=int(seed),
    )


def register_bundle_k_stochastic_shader_pass() -> None:
    from .terrain_pipeline import TerrainPassController

    TerrainPassController.register_pass(
        PassDefinition(
            name="stochastic_shader",
            func=pass_stochastic_shader,
            requires_channels=("height",),
            produces_channels=("stochastic_uv_mask",),
            seed_namespace="stochastic_shader",
            requires_scene_read=False,
            description="Bundle K: Heitz 2019 stochastic tile-sampling (hash offsets, histogram-preserving, UV rotation; roughness_variation owned by roughness_driver)",
        )
    )


__all__ = [
    "StochasticShaderTemplate",
    "build_stochastic_sampling_mask",
    "build_hex_tiling_mask",
    "export_unity_shader_template",
    "pass_stochastic_shader",
    "register_bundle_k_stochastic_shader_pass",
]
