using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

namespace VeilBreakers.TerrainImport
{
    /// <summary>
    /// Runtime GPU-instanced foliage renderer for foliage_placement_manifest.json.
    /// Keeps the retired DCC scatter handoff replaced by an engine-native draw path.
    /// </summary>
    [ExecuteAlways]
    public sealed class VbFoliageManifestRenderer : MonoBehaviour
    {
        [Serializable]
        public sealed class FoliagePrototype
        {
            public string SpeciesKey = string.Empty;
            public int MeshId = -1;
            public Mesh[] LodMeshes = Array.Empty<Mesh>();
            public Material Material;
            public ShadowCastingMode ShadowCasting = ShadowCastingMode.On;
            public bool ReceiveShadows = true;
        }

        [Serializable]
        private sealed class ManifestPayload
        {
            public float[] lod_distances_m = Array.Empty<float>();
            public MeshLibraryEntry[] mesh_library = Array.Empty<MeshLibraryEntry>();
            public InstanceEntry[] instances = Array.Empty<InstanceEntry>();
        }

        [Serializable]
        private sealed class MeshLibraryEntry
        {
            public int mesh_id;
            public string species_key = string.Empty;
            public string unity_render_mode = string.Empty;
            public string render_batch_key = string.Empty;
        }

        [Serializable]
        private sealed class InstanceEntry
        {
            public int mesh_id;
            public float[] position_world = Array.Empty<float>();
            public float rotation_y_rad;
            public float scale = 1.0f;
            public float[] scale_xyz = Array.Empty<float>();
            public int lod_level;
            public float[] tint_rgb = Array.Empty<float>();
        }

        private sealed class DrawBatch
        {
            public FoliagePrototype Prototype;
            public int LodIndex;
            public readonly List<Matrix4x4> Matrices = new List<Matrix4x4>(1023);
            public readonly List<Vector4> Tints = new List<Vector4>(1023);
            public readonly Matrix4x4[] MatrixBuffer = new Matrix4x4[1023];
            public readonly Vector4[] TintBuffer = new Vector4[1023];
        }

        [Tooltip("Manifest text asset generated by scripts/export_foliage_manifest.py.")]
        public TextAsset ManifestJson;

        [Tooltip("Runtime prototypes keyed by mesh_id or species_key from the manifest.")]
        public FoliagePrototype[] Prototypes = Array.Empty<FoliagePrototype>();

        [Tooltip("Camera used for distance LOD and culling. Defaults to Camera.main.")]
        public Camera ViewCamera;

        [Tooltip("Transform used for distance LOD and culling. Defaults to ViewCamera.")]
        public Transform ViewTarget;

        [Tooltip("Convert terrain-space [x,row,height] positions into Unity [x,height,z].")]
        public bool ConvertTerrainXzyToUnityXyz = false;

        [Tooltip("Treat manifest position_world values as absolute Unity world coordinates.")]
        public bool PositionsAreWorldSpace = true;

        [Tooltip("Maximum draw distance for GPU foliage instances.")]
        public float CullDistanceM = 300.0f;

        [Tooltip("Hard safety cap for runtime instances drawn by this component.")]
        public int MaximumInstances = 100000;

        [Tooltip("Layer used by Graphics.DrawMeshInstanced.")]
        public int RenderLayer = 0;

        [Tooltip("Shader vector-array property used for per-instance tint.")]
        public string TintShaderProperty = "_BaseColor";

        [Tooltip("Enable material instancing if an assigned material forgot to enable it.")]
        public bool ForceEnableMaterialInstancing = true;

        public int LoadedInstanceCount { get; private set; }
        public int DrawnInstanceCount { get; private set; }
        public int MissingPrototypeCount { get; private set; }

        private readonly Dictionary<int, FoliagePrototype> _prototypeByMeshId =
            new Dictionary<int, FoliagePrototype>();
        private readonly Dictionary<string, FoliagePrototype> _prototypeBySpecies =
            new Dictionary<string, FoliagePrototype>(StringComparer.Ordinal);
        private readonly Dictionary<int, string> _speciesByMeshId =
            new Dictionary<int, string>();
        private readonly Dictionary<string, DrawBatch> _batches =
            new Dictionary<string, DrawBatch>(StringComparer.Ordinal);
        private MaterialPropertyBlock _propertyBlock;

        private ManifestPayload _manifest;

        // HOTFIX-7e: track floating-origin shift so GPU foliage positions
        // stay co-located with terrain after VbFloatingOrigin recenters the
        // world. Without this, baked manifest positions drift kilometers away
        // from the terrain GameObject after the first ShiftWorld() call.
        private VbFloatingOrigin _floatingOrigin;
        private Vector3 _originOffset = Vector3.zero;

        private void OnEnable()
        {
            EnsurePropertyBlock();
            ReloadManifest();
            SubscribeFloatingOrigin();
        }

        private void OnDisable()
        {
            UnsubscribeFloatingOrigin();
        }

        private void OnValidate()
        {
            _manifest = null;
            LoadedInstanceCount = 0;
            BuildPrototypeLookup();
        }

        private void LateUpdate()
        {
            if (_manifest == null)
            {
                ReloadManifest();
            }

            RenderManifest();
        }

        public void ReloadManifest()
        {
            BuildPrototypeLookup();
            _manifest = null;
            LoadedInstanceCount = 0;

            if (ManifestJson == null || string.IsNullOrWhiteSpace(ManifestJson.text))
            {
                return;
            }

            _manifest = JsonUtility.FromJson<ManifestPayload>(ManifestJson.text);
            if (_manifest == null || _manifest.instances == null)
            {
                _manifest = null;
                return;
            }

            _speciesByMeshId.Clear();
            if (_manifest.mesh_library != null)
            {
                foreach (var entry in _manifest.mesh_library)
                {
                    if (entry == null)
                    {
                        continue;
                    }

                    _speciesByMeshId[entry.mesh_id] = entry.species_key ?? string.Empty;
                }
            }

            LoadedInstanceCount = _manifest.instances.Length;
        }

        public void RenderManifest()
        {
            EnsurePropertyBlock();
            DrawnInstanceCount = 0;
            MissingPrototypeCount = 0;
            ClearBatches();

            if (_manifest == null || _manifest.instances == null || _manifest.instances.Length == 0)
            {
                return;
            }

            var target = ResolveTarget();
            if (target == null)
            {
                return;
            }

            var limit = MaximumInstances <= 0
                ? _manifest.instances.Length
                : Mathf.Min(MaximumInstances, _manifest.instances.Length);

            for (var index = 0; index < limit; index++)
            {
                var instance = _manifest.instances[index];
                if (instance == null || !TryResolvePrototype(instance.mesh_id, out var prototype))
                {
                    MissingPrototypeCount++;
                    continue;
                }

                var position = ToUnityPosition(instance.position_world);
                var distance = Vector3.Distance(target.position, position);
                if (distance > CullDistanceM)
                {
                    continue;
                }

                var lodIndex = SelectLod(instance.lod_level, distance, prototype);
                var mesh = MeshForLod(prototype, lodIndex);
                if (mesh == null || prototype.Material == null)
                {
                    MissingPrototypeCount++;
                    continue;
                }

                if (ForceEnableMaterialInstancing)
                {
                    prototype.Material.enableInstancing = true;
                }

                var scale = ToUnityScale(instance);
                var rotation = Quaternion.Euler(0.0f, Mathf.Rad2Deg * instance.rotation_y_rad, 0.0f);
                var matrix = Matrix4x4.TRS(position, rotation, scale);
                var tint = ToTint(instance.tint_rgb);
                var batch = GetBatch(prototype, lodIndex);
                batch.Matrices.Add(matrix);
                batch.Tints.Add(tint);
            }

            FlushBatches();
        }

        private void EnsurePropertyBlock()
        {
            if (_propertyBlock == null)
            {
                _propertyBlock = new MaterialPropertyBlock();
            }
        }

        private void BuildPrototypeLookup()
        {
            _prototypeByMeshId.Clear();
            _prototypeBySpecies.Clear();

            foreach (var prototype in Prototypes)
            {
                if (prototype == null)
                {
                    continue;
                }

                if (prototype.MeshId >= 0)
                {
                    _prototypeByMeshId[prototype.MeshId] = prototype;
                }

                if (!string.IsNullOrEmpty(prototype.SpeciesKey))
                {
                    _prototypeBySpecies[prototype.SpeciesKey] = prototype;
                }
            }
        }

        private bool TryResolvePrototype(int meshId, out FoliagePrototype prototype)
        {
            if (_prototypeByMeshId.TryGetValue(meshId, out prototype))
            {
                return true;
            }

            if (_speciesByMeshId.TryGetValue(meshId, out var species)
                && _prototypeBySpecies.TryGetValue(species, out prototype))
            {
                return true;
            }

            prototype = null;
            return false;
        }

        private Transform ResolveTarget()
        {
            if (ViewTarget != null)
            {
                return ViewTarget;
            }

            var camera = ViewCamera != null ? ViewCamera : Camera.main;
            return camera != null ? camera.transform : null;
        }

        private Vector3 ToUnityPosition(float[] raw)
        {
            if (raw == null || raw.Length < 3)
            {
                return transform.position;
            }

            var position = ConvertTerrainXzyToUnityXyz
                ? new Vector3(raw[0], raw[2], raw[1])
                : new Vector3(raw[0], raw[1], raw[2]);
            var worldPosition = PositionsAreWorldSpace ? position : transform.TransformPoint(position);
            // HOTFIX-7e: subtract accumulated floating-origin offset so GPU
            // foliage tracks the same recentering applied to ShiftRoots.
            return worldPosition - _originOffset;
        }

        private void SubscribeFloatingOrigin()
        {
            // No singleton on VbFloatingOrigin — fall back to a scene scan.
            // Limitation: if a VbFloatingOrigin is added after foliage OnEnable,
            // foliage must be toggled or the new origin component must call
            // BindFloatingOrigin() explicitly.
            if (_floatingOrigin == null)
            {
                _floatingOrigin = FindObjectOfType<VbFloatingOrigin>();
            }
            if (_floatingOrigin != null)
            {
                _floatingOrigin.OnOriginMoved.AddListener(HandleOriginShifted);
                _originOffset = _floatingOrigin.AccumulatedOffset;
            }
        }

        private void UnsubscribeFloatingOrigin()
        {
            if (_floatingOrigin != null)
            {
                _floatingOrigin.OnOriginMoved.RemoveListener(HandleOriginShifted);
            }
        }

        /// <summary>
        /// Bind to a VbFloatingOrigin discovered after this renderer initialized.
        /// </summary>
        public void BindFloatingOrigin(VbFloatingOrigin origin)
        {
            UnsubscribeFloatingOrigin();
            _floatingOrigin = origin;
            if (_floatingOrigin != null)
            {
                _floatingOrigin.OnOriginMoved.AddListener(HandleOriginShifted);
                _originOffset = _floatingOrigin.AccumulatedOffset;
            }
        }

        // HOTFIX-7e: OnOriginMoved supplies (currentAccumulatedOffset, previousOffset).
        // We cache the accumulated offset and subtract it during ToUnityPosition
        // so manifest world positions track the shifted ShiftRoots transforms.
        private void HandleOriginShifted(Vector3 accumulatedOffset, Vector3 previousOffset)
        {
            _originOffset = accumulatedOffset;
        }

        private static Vector3 ToUnityScale(InstanceEntry instance)
        {
            if (instance.scale_xyz != null && instance.scale_xyz.Length >= 3)
            {
                return new Vector3(
                    Mathf.Max(0.001f, instance.scale_xyz[0]),
                    Mathf.Max(0.001f, instance.scale_xyz[1]),
                    Mathf.Max(0.001f, instance.scale_xyz[2])
                );
            }

            var scale = Mathf.Max(0.001f, instance.scale);
            return new Vector3(scale, scale, scale);
        }

        private int SelectLod(int manifestLod, float distance, FoliagePrototype prototype)
        {
            var distanceLod = 0;
            var lodDistances = _manifest.lod_distances_m;
            if (lodDistances != null && lodDistances.Length > 0)
            {
                while (distanceLod < lodDistances.Length - 1 && distance > lodDistances[distanceLod])
                {
                    distanceLod++;
                }
            }

            var lod = Mathf.Max(0, Mathf.Max(manifestLod, distanceLod));
            return Mathf.Min(lod, Mathf.Max(0, prototype.LodMeshes.Length - 1));
        }

        private static Mesh MeshForLod(FoliagePrototype prototype, int lodIndex)
        {
            if (prototype.LodMeshes == null || prototype.LodMeshes.Length == 0)
            {
                return null;
            }

            return prototype.LodMeshes[Mathf.Clamp(lodIndex, 0, prototype.LodMeshes.Length - 1)];
        }

        private static Vector4 ToTint(float[] tint)
        {
            if (tint == null || tint.Length < 3)
            {
                return Vector4.one;
            }

            return new Vector4(tint[0], tint[1], tint[2], 1.0f);
        }

        private DrawBatch GetBatch(FoliagePrototype prototype, int lodIndex)
        {
            var key = prototype.GetHashCode() + "::" + lodIndex;
            if (_batches.TryGetValue(key, out var batch))
            {
                return batch;
            }

            batch = new DrawBatch
            {
                Prototype = prototype,
                LodIndex = lodIndex,
            };
            _batches[key] = batch;
            return batch;
        }

        private void ClearBatches()
        {
            foreach (var batch in _batches.Values)
            {
                batch.Matrices.Clear();
                batch.Tints.Clear();
            }
        }

        private void FlushBatches()
        {
            foreach (var batch in _batches.Values)
            {
                var mesh = MeshForLod(batch.Prototype, batch.LodIndex);
                if (mesh == null || batch.Prototype.Material == null)
                {
                    continue;
                }

                for (var start = 0; start < batch.Matrices.Count; start += 1023)
                {
                    var count = Mathf.Min(1023, batch.Matrices.Count - start);
                    batch.Matrices.CopyTo(start, batch.MatrixBuffer, 0, count);
                    batch.Tints.CopyTo(start, batch.TintBuffer, 0, count);

                    _propertyBlock.Clear();
                    if (!string.IsNullOrEmpty(TintShaderProperty))
                    {
                        _propertyBlock.SetVectorArray(TintShaderProperty, batch.TintBuffer);
                    }

                    Graphics.DrawMeshInstanced(
                        mesh,
                        0,
                        batch.Prototype.Material,
                        batch.MatrixBuffer,
                        count,
                        _propertyBlock,
                        batch.Prototype.ShadowCasting,
                        batch.Prototype.ReceiveShadows,
                        RenderLayer
                    );
                    DrawnInstanceCount += count;
                }
            }
        }
    }
}
