from typing import Any

class BlenderConnection:
    def __init__(
        self,
        host: str = ...,
        port: int = ...,
        timeout: float = ...,
        **kwargs: Any,
    ) -> None: ...
    def _send_on_socket(self, command: Any) -> Any: ...
    def _sync_send(self, command: Any) -> Any: ...
    def disconnect(self) -> None: ...
    def is_alive(self) -> bool: ...
