from typing import TypeAlias

Color: TypeAlias = tuple[int, int, int]

def contrast_ratio(foreground: Color, background: Color) -> float: ...
def check_wcag_aa(foreground: Color, background: Color) -> bool: ...
def parse_color(value: str) -> Color | None: ...
